
# connect = "127.0.0.1:3000"
# turn values:
#    STOPPED = 0,
#    GO= 1,
#    ReadyUp = 2,
#    ReadyDown = 3,
#listen = "(address):3000"
connect = "192.168.5.45:3000"
[Properties]
turn = 0
speed = 400
pt = 2
